apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-script
data:
  {{- $files := .Files }}
  {{- range tuple "xapp.py" "script2.py" }}
  {{ . }}: |-
{{ $files.Get . | trim | nindent 4 }}
  {{- end }}
