apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-script
data:
  {{- $files := .Files }}
  {{- range tuple "xapp.py" }}
  {{ . }}: |-
    {{ $files.Get . | indent 2}}    
  {{- end }}
